name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
      - name: Run backend tests
        run: |
          cd backend
          npm test
      # Puedes agregar aquí pasos para pruebas de frontend si lo deseas

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Ejemplo para Vercel (requiere configuración de token)
      - name: Deploy to Vercel
        run: echo "Configura aquí el despliegue automático a Vercel, Heroku, etc."
